### ISSUE TITLE
"Error installing dependencies" after firmware upgrade 1.0.4

### ISSUE THREAD

**Issue by clemensc** [frozenjava/EvilPortalNano#1]
As reported here:
https://forums.hak5.org/index.php?/topic/37319-release-104-codename-aardwolf-ambulance/page-3#entry271442
and here:
https://forums.hak5.org/index.php?/topic/37081-evilportal/#entry271428

**Comment by frozenjava** [comment]
This is a bigger issue outside of the Evil Portal module with the 1.0.4 firmware. I'm working with Sebkinne to get it resolved. Thanks for bringing it up!

**Comment by clemensc** [comment]
NP, all I did was whine. :) Thanks for being on top of this so quickly. I'll be looking forward to the next fw update.
