### ISSUE TITLE
No web notification after attemp to log in

### ISSUE THREAD

**Issue by pdelteil** [frozenjava/EvilPortalNano#19]
Using the latest pineapple firmware (2.1) and latest evilportal.

I tried the google portal, I found the credentials on the logs files (/sd/evilportal-logs) but nothing happened on the web UI.

**Comment by gerrogerro** [comment]
For web notification edit your "MyPortal.php".

If you want for example being notified about the "$line" parameter,  after  the "file_put_contents etc.." string, add this: 

exec("pineapple notify '$line' ");

before the "}"

You need to exec $line or $password , $email or whatever you want ti be notified about

**Comment by pdelteil** [comment]
@gerrogerro Thanks for your answer. I thought notifications were working since the Readme info says it.


![screenshot from 2018-06-21 10-33-07](https://user-images.githubusercontent.com/20244863/41725847-d1b46a30-753e-11e8-9a4e-d05cf76cc4df.png)

I will try your code.

**Comment by frozenjava** [comment]
@pdelteil where are you reading this from? Web notifications is not part of the standard behavior of Evil Portal. Its not a bad thing for me to add in the future but thats not currently how it works.

**Comment by frozenjava** [comment]
Anyways not sure where you are reading that from. It was never part of EP but it's a good suggestion so I added it in commit #94d1b90 which is now in nightly.
