### ISSUE TITLE
Documentation for Portals how to edit 

### ISSUE THREAD

**Issue by H4xl0r** [frozenjava/EvilPortalNano#22]
How to use  writeLog($email' - '$pwd');
                    notify($email' - '$pwd");

where to put post data ? 

please one example page for the new write etc ....

**Comment by H4xl0r** [comment]
Ok that is a hint :-) 
but got some other problems too , could live with that logfile...

when i go to view, from the page (eg. google-login) there are no logs shown ...even if there are some (wrong location ) as i said i am using the google-login .. so maybe u could take your example on that :-) 

he is not redirecting ... he says you are not authenticated, but gives internet ...
Strange things happen here  

using the nighty version of evil...
thanks for the fast repl.

**Comment by H4xl0r** [comment]
the problem with your solution is , i dont know if he gets the Success 
because redirecting wrong ( clients shows u ware not auth. even when creds given)

**Comment by frozenjava** [comment]
I started working on it here:
https://github.com/frozenjava/EvilPortalNano/wiki

Also this might help answer some questions:
https://forums.hak5.org/topic/37874-official-evilportal/?do=findComment&comment=309921

But the documentation is an ongoing initiative and I'll be writing more docs in the near future.
