### ISSUE TITLE
EvilPortal and PineAP do not work at the same time

### ISSUE THREAD

**Issue by EastwindZL** [frozenjava/EvilPortalNano#23]
I am using Nano

please help me I want each user of the PinaAP module to receive a portal authentication page.

However, the authentication page will not be automatically popped up after connecting to the AP!

**Comment by H4xl0r** [comment]
Works for me .... PineAP sends the ssids 
client connects ... 
and gets the popup...

**Comment by H4xl0r** [comment]
Reset Maybe ?
Running the latest firmware of Nano? .. reinstall Evil Portal ? 
I have the settings as follows 
pineAP Running on Boot enabled 
EvilAP Runnning on Boot ebabled 

which kind  of portal are u using ? 
the https://github.com/kbeflo/evilportals.git portals ?

**Comment by EastwindZL** [comment]
@H4xl0r Another way is to port PineAP and EvilPortal to kali.
