### ISSUE TITLE
Skeleton/Default Portal and HTTPS issues.

### ISSUE THREAD

**Issue by MinimotoMusashi** [frozenjava/EvilPortalNano#24]
When creating a new portal. At the top of the index.php script where it's parsing the requested URL.

It's currently:
`$destination = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['HTTP_URI'] . "";`
And should be:
`$destination = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];`
And this would allow http or https:
`$destination = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";`

Also redirecting doesn't work. What function starts handleAuthorization? onSuccess() is working, but 
redirect() isn't.

In MyPortal script your notes say that we can put in what we want, but the redirect() function is
inside the protected handleAuthorization.

Maybe leaving redirect inside the public function in the myportal script?

**Comment by H4xl0r** [comment]
Yes had the same problem svolved via : 

```
public function showSuccess()
    {
        // Calls default success message
        parent::showSuccess();
        header('Location: https://www.google.com');
    }
}

```
in myportal.txt 

The problem is that the redirect is not working , i think because the request url is not working, eg when connecting without request . there is no request url ...

**Comment by kbeflo** [comment]
@H4xl0r are you currently using the latest Pineapple firmware and EvilPortalNano?

**Comment by H4xl0r** [comment]
Can be closed But we still need to rethink the redirect function ....
any hints here ? 

the handle authorization is done via 
https://github.com/frozenjava/EvilPortalNano/blob/master/EvilPortal/includes/api/Portal.php

Portal.php 

the function is 

 ```
protected function redirect()
    {
        header("Location: {$this->request->target}", true, 302);
    }

i think here is the error ?

```

**Comment by H4xl0r** [comment]
For the redirect you need to have something like this inside the form post of the index.php 

like 
```
<form method="POST" action="/captiveportal/index.php">
                <input type="hidden" name="target" value="<?=$destination?>">
                <button type="submit">Authorize</button>
            </form>
```

the form tells where the redirect should go , so you need to inculde that in your form 

or you change it name="target" value="https://google.de">

Like 

```
<form method="POST" action="/captiveportal/index.php">
                <input type="hidden" name="target" value="https://google.com">
                <button type="submit">Authorize</button>
            </form>
```

**Comment by H4xl0r** [comment]
@frozenjava please close 
and thanks to @MinmotoMusashi  for the hint , good work !
