### ISSUE TITLE
redirect HTTPS sites

### ISSUE THREAD

**Issue by joker5bb** [frozenjava/EvilPortalNano#4]
The best way to accomplish this is not to redirect https but to setup the Evil Portal to do incorporate captive portal detection process for all OS.

https://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection
https://sudoroom.org/wiki/Mesh/Firmware/Splash_page

    # For iOS
if ($http_user_agent ~* (CaptiveNetworkSupport) ) {
        return 302 http://hotspot.localnet/hotspot.html;
    }

    # For others
    location / {
        return 302 http://hotspot.localnet/;
    }

**Comment by oliversalzburg** [comment]
I don't understand this suggestion. If I set up the Pineapple to return invalid URLs for the captive portal detection, that will make my client complain about being in a captive portal, but it won't prevent the client from opening resources through HTTPS.

What am I missing?

**Comment by H4xl0r** [comment]
can be closed Pulled
