### ISSUE TITLE
Make portals available w/o internet connection

### ISSUE THREAD

**Issue by wicked** [frozenjava/EvilPortalNano#5]
Using the Evil Portal 2.9 module, captive portals only appear when I'm connected to the internet using ICS. Is there a way to make the portals available even without internet connection?

**Comment by frozenjava** [comment]
I'm not sure what you mean. Are you unable to see the list of available portals in the Work Bench or clients aren't getting directed to a portal if there is no internet connection?

**Comment by wicked** [comment]
Clients aren't getting directed to the portal when there is no internet connection. I'm using https://github.com/kbeflo/evilportal-templates

**Comment by wicked** [comment]
The latter @frozenjava

**Comment by kn0wledge** [comment]
Hey @frozenjava , sent you a mail on josh@frozendevelopments lemme know what you think.

Sorry for Hijaking the thread , but yeah I agree with @wicked , if all files are available offline, can the captive portal load without internet ? Also , anyway to redirect to a specific site after authorization ?
