### ISSUE TITLE
Still developing 3.0?

### ISSUE THREAD

**Issue by kn0wledge** [frozenjava/EvilPortalNano#6]
Hey @frozenjava , havent heard from you in a while, still working on the dev of 3.0?

**Comment by frozenjava** [comment]
Hi @kn0wledge , 
I'm swamped with other things right now that pay the bills so unfortunately Evil Portal has had to take a spot on the back burner for a while. I do plan on getting it finished up and released as soon as I have some time to dedicate to it again. Feel free to make pull requests and I'll get them merged.

**Comment by kn0wledge** [comment]
@frozenjava I hear you. Paying the bills is priority . Not much of a coder but if I am ever able to contribute , I would. A great initiative
