### ISSUE TITLE
Portal Workbench

### ISSUE THREAD

**Issue by b0n3zx** [frozenjava/EvilPortalNano#8]
On the Nano the work bench with portals looks great but on the Tetra its not the same.  I leave a link to a screen shot I took.  Its been like this for a while.  Been using 2.9beta and recently just started using the Nightly build.  Screen shot here ---- http://imgur.com/pOtpNZQ

**Comment by frozenjava** [comment]
Strange... which version of EP were you using in that screenshot?

**Comment by frozenjava** [comment]
If you insert an SD card does it fix the problem?

**Comment by b0n3zx** [comment]
This was done 5/25 off the Nightly build and Development build before that I think v2.9.  The screenshot is from the Tetra.  On the Nano with SD card inserted the Workbench looks fine.

**Comment by frozenjava** [comment]
This has been resolved.
